### ISSUE TITLE
Gif roll lag terribly

### ISSUE THREAD

**Issue by the-eric-kwok** [isklikas/GIFRoll#1]
Here's the video: [https://youtu.be/1wTjf-gjtos](https://youtu.be/1wTjf-gjtos)
Animation lag terribly if I swipe to switch between gif and normal photos.

**Comment by isklikas** [comment]
Thank you! This is a known bug however I no longer have a jailbroken device to help on providing a fix. I might have a look in the code and ask for help from testers however.
